export enum ErrorCodes {
  PASSWORD_RESET_RATE_LIMITED = "PASSWORD_RESET_RATE_LIMITED",
  PASSWORD_RESET_INVALID = "PASSWORD_RESET_INVALID",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  UNAUTHORIZED = "UNAUTHORIZED",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
